### ISSUE TITLE
Silicio outdated?

### ISSUE THREAD

**Issue by accessdenied0** [LatvianModder/Silicio#1]
Dear @LatvianModder,

I guess Silicio is outdated since the last 1.6.11.1 update, because I got a crash which looks like something like that: http://pastebin.com/ec1uckbP...

Anyway... I just have a additional suggestion for your mod: Can you please add Silicon to the OreDictionary? I ask this because I use AE2 and EnderIO in my world and both uses Silicon, too.

respectful, 

access_denied

**Comment by LatvianModder** [comment]
Yes, I didn't update it for this version (It will be updated later, I just don't want to make half broken version public in Curse), so you have to use older version of LatCoreMC.

Tho, if you are only interested in using Silicio for item / fluid / energy transport, you can use dev version from here:

https://www.dropbox.com/sh/o52fmk1t8v7ui5y/AADVKWxZxtAFag4cjQ4hpcKea?dl=0

**Comment by LatvianModder** [comment]
And Silicon item in OD - that will be done eventually

**Comment by accessdenied0** [comment]
@LatvianModder,

Thank you very much, I'll wait for the stable release. I really like your mods.

access_denied
